# Generated by Django 5.0.7 on 2024-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
