# Generated by Django 5.0.7 on 2024-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0002_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('COUPON', 'Coupon'), ('QUANTITY', 'Quantity-based')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='quantity_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
