# Generated by Django 5.0.7 on 2024-11-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
    ]
