# Generated by Django 5.0.7 on 2024-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0005_alter_order_email_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='blackwilbur.OrderItem', to='blackwilbur.product'),
        ),
    ]
