# Generated by Django 5.0.7 on 2024-10-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0006_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
