# Generated by Django 5.0.7 on 2024-11-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0007_remove_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
