# Generated by Django 5.0.7 on 2024-10-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0008_rename_product_orderitem_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
