# Generated by Django 5.0.7 on 2024-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0009_remove_orderitem_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_coupon_applied',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
