# Generated by Django 5.0.7 on 2024-10-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0009_rename_product_id_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
