# Generated by Django 5.0.7 on 2024-10-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0013_alter_productvariation_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
