# Generated by Django 5.0.7 on 2024-11-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0014_remove_image_url_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('product', 'Product Image'), ('carousel', 'Carousel Image'), ('other', 'Other Image')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
