# Generated by Django 5.0.7 on 2024-11-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0015_image_image_type_alter_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_id',
        ),
    ]
