# Generated by Django 5.0.7 on 2024-11-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackwilbur', '0016_rename_product_image_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_id',
            field=models.CharField(blank=True, help_text='Optional product identifier', max_length=100, null=True),
        ),
    ]
